name: "Deploy KDY Docs"
on:
  workflow_run:
    workflows: ["Docs Check"]
    types: [completed]
    branches:
      - master
      - main
jobs:
  deploy-kdy-docs:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name '${{github.actor}}'
          git config user.email '${{github.actor}}'@users.noreply.github.com
      - uses: DeterminateSystems/nix-installer-action@main 
      - uses: DeterminateSystems/magic-nix-cache-action@main 
      # - uses: rrbutani/use-nix-shell-action@v1
      #   with:
      #     devShell: .#default # this is the default
      # - run: nix -L flake check 
      - name: Deploy gh-pages 
        run: |
          nix develop --command \
            mkdocs gh-deploy
